IMAGE_NAME = ubuntu_tesseract_python

build:
	# docker build -t $(IMAGE_NAME) .
	docker compose build

run:
	# docker run -it $(IMAGE_NAME) /bin/bash
	# docker run -it -p 8000:8000 -p 8501:8501 $(IMAGE_NAME) /bin/bash
	# docker run -d --network=host  -p 8000 -p 8501 $(IMAGE_NAME) 
	docker run  -p 8000:8000 -p 8501:8501 $(IMAGE_NAME)
clean:
	docker stop $$(docker ps -a -q) 2>/dev/null
	docker rm $$(docker ps -a -q) 2>/dev/null
	docker rmi $(IMAGE_NAME) 2>/dev/null
stop:
	docker stop $$(docker ps -a -q) 2>/dev/null

.PHONY: build run clean